name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDWhwvrFS3zKE4dKDYvrDziYcrBIlWS3XmC+jFeNDXPg

      - name: Deploy code to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.235.68.78 << 'EOF'
            cd /home/ubuntu/AWS
            git pull origin main
            npm install
            node index.js
          EOF
